alias wifi-list="nmcli device wifi list"
alias timezone-toronto="sudo timedatectl set-timezone America/Toronto"
alias timezone-amsterdam="sudo timedatectl set-timezone Europe/Amsterdam"
alias decrypt-hyprland-cache="gocryptfs /home/miso/.local/share/.docs/.cache-hyprland-old/ ~/.private/"
alias encrypt-hyprland-cache="umount ~/.private"
